# Generated by Django 4.0.3 on 2022-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_alter_editor_options_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
    ]
